version: '3.3'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=api
      - DOCKER_INFLUXDB_INIT_PASSWORD=apipasswd
      - DOCKER_INFLUXDB_INIT_ORG=fing
      - DOCKER_INFLUXDB_INIT_BUCKET=series

  api:
    image: service-api:latest
    ports:
      - '8000:8000'


volumes:
    influxdb-storage:
